### ISSUE TITLE
Is it possible to use without using expo?

### ISSUE THREAD

**Issue by radelcom** [nattatorn-dev/react-native-user-profile#59]
just wondering if it is possible to use without using expo?

**Comment by ibernadas** [comment]
radelcom, were you able to use it without expo? I see no answers to your question.

**Comment by AasthaGoyalgit** [comment]
Can this code run on vscode??


I'm getting error
Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
